# This file was generated by GoReleaser. DO NOT EDIT.
cask "sciscope-tui" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "f77ccebf96fbb519d5bee85e0262b9aa013cee70ef5fe30e015d6350da0262ba"
      url "https://github.com/Timcai06/SciScope/releases/download/v#{version}/sciscope-tui_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6981aa3714e5becbb217a3c447fc5fda05605c4992b875c8fbb4ed954939be95"
      url "https://github.com/Timcai06/SciScope/releases/download/v#{version}/sciscope-tui_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "522c0715e73f79847c32521143d9d6743dc35cd72d6337ae06b80f49f607b977"
      url "https://github.com/Timcai06/SciScope/releases/download/v#{version}/sciscope-tui_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2423e8c0b3a3271853d091cecd68642b637367db3655aa42a926c32f404af015"
      url "https://github.com/Timcai06/SciScope/releases/download/v#{version}/sciscope-tui_linux_arm64.tar.gz"
    end
  end

  name "sciscope-tui"
  desc "SciScope 科研智能体终端客户端(Bubble Tea, 经 SSE 连接后端)"
  homepage "https://github.com/Timcai06/SciScope"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sciscope-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sciscope-tui"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    运行离线演示:
      sciscope-tui --demo

    连接真实后端:
      make backend && make llm
      sciscope-tui

    或用 SCISCOPE_BACKEND=https://你的后端 指向远程服务。
  EOS
end
