# This file was generated by GoReleaser. DO NOT EDIT.
cask "sciscope-tui" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "4b4a0bf36c22ad11650f26e02b6387109167b50a28b0041a049f1c735b53c96f"
      url "https://github.com/Timcai06/SciScope/releases/download/v#{version}/sciscope-tui_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f85201f372d0368a227a9d39ac7c68ee324634463953758cdbbdb593c1d0f26"
      url "https://github.com/Timcai06/SciScope/releases/download/v#{version}/sciscope-tui_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "40e7da9e3a6edc9c0a31aa258f236780fc6090f739648a03f224318dc7f2a94a"
      url "https://github.com/Timcai06/SciScope/releases/download/v#{version}/sciscope-tui_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e7677c7f0b2f516d191eadfe5b15ad951836183902ac3991fdb48d5146b2e763"
      url "https://github.com/Timcai06/SciScope/releases/download/v#{version}/sciscope-tui_linux_arm64.tar.gz"
    end
  end

  name "sciscope-tui"
  desc "SciScope 科研智能体终端客户端(Bubble Tea, 经 SSE 连接后端)"
  homepage "https://github.com/Timcai06/SciScope"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sciscope-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sciscope-tui"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    运行离线演示:
      sciscope-tui --demo

    连接真实后端:
      make backend && make llm
      sciscope-tui

    或用 SCISCOPE_BACKEND=https://你的后端 指向远程服务。
  EOS
end
