# This file was generated by GoReleaser. DO NOT EDIT.
cask "sciscope-tui" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "b2606c9bdda6b0b0fdfab72f9a6494b960269f66aebd2e9c9cef93537af4691a"
      url "https://github.com/Timcai06/SciScope/releases/download/v#{version}/sciscope-tui_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "473d2ebab12d4b5b075566b4fbced5a1699072f136d3fb99b9643a0dbd8ba316"
      url "https://github.com/Timcai06/SciScope/releases/download/v#{version}/sciscope-tui_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a1470ca7922b51c36ca4e4e2c20a8a6244696049cc4d2426e350640f171469cd"
      url "https://github.com/Timcai06/SciScope/releases/download/v#{version}/sciscope-tui_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2c9dd7c59fc405b8d69c343cdeed06597a2609abb86a07bf86cc2111e2404324"
      url "https://github.com/Timcai06/SciScope/releases/download/v#{version}/sciscope-tui_linux_arm64.tar.gz"
    end
  end

  name "sciscope-tui"
  desc "SciScope 科研智能体终端客户端(Bubble Tea, 经 SSE 连接后端)"
  homepage "https://github.com/Timcai06/SciScope"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sciscope-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sciscope-tui"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    运行离线演示:
      sciscope-tui --demo

    连接真实后端:
      make backend && make llm
      sciscope-tui

    或用 SCISCOPE_BACKEND=https://你的后端 指向远程服务。
  EOS
end
